FROM flink:1.18

COPY jars/flink-sql-connector-kafka-3.2.0-1.18.jar /opt/flink/lib/
COPY jars/iceberg-flink-runtime-1.18-1.9.2.jar /opt/flink/lib/
COPY jars/iceberg-aws-bundle-1.9.2.jar /opt/flink/lib/
COPY jars/hadoop-client-api-3.3.6.jar /opt/flink/lib/
COPY jars/hadoop-client-runtime-3.3.6.jar /opt/flink/lib/