services:
  superset:
    networks:
      - default
      - stream-shared
  superset-worker:
    networks:
      - default
      - stream-shared
  superset-worker-beat:
    networks:
      - default
      - stream-shared
  superset-init:
    networks:
      - default
      - stream-shared

networks:
  stream-shared:
    external: true
